model:
  base_learning_rate: 1.0e-06
  target: ldm.models.autoencoder.VQModel
  params:
    embed_dim: 1
    n_embed: 16384
    monitor: val/rec_loss
    ddconfig:
      double_z: false
      z_channels: 1
      resolution: 512
      in_channels: 1
      out_ch: 1
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 32
      dropout: 0.0
    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 1
        disc_start: 20000
        disc_weight: 0.75
        codebook_weight: 1.0
        perceptual_weight: 0.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 4
    wrap: true
    train:
      target: ldm.data.xcat_Motion.XCATTrain
      params: {}
    validation:
      target: ldm.data.xcat_Motion.XCATValidation
      params: {}
    test:
      target: ldm.data.xcat_Motion.XCATTest
      params: {}

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 200
        max_images: 8
        increase_log_steps: false
  trainer:
    benchmark: true
    accumulate_grad_batches: 4
    max_epochs: 50
    default_root_dir: ./logs/xcat-autoencoder
    val_check_interval: 1.0
    gpus: 1
